In [144]:
import numpy as np
import pandas as pd

In [145]:
from sklearn.preprocessing import StandardScaler

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
from sklearn import svm

In [148]:
from sklearn.metrics import accuracy_score

In [149]:
diabetes_dataset=pd.read_csv('/content/diabetes.csv')


In [150]:
diabetes_dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [151]:
diabetes_dataset.shape

(768, 9)

In [152]:
# getting the statistical data of dataframe

In [153]:
diabetes_dataset['Outcome'].value_counts()


0    500
1    268
Name: Outcome, dtype: int64

In [154]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [155]:
X=diabetes_dataset.drop(columns="Outcome",axis=1)

In [156]:
Y=diabetes_dataset['Outcome']

In [157]:
# Standard scaler is used for standardising the data.
# purpose of doing this is to have all values ranging from 0 to 1 taaki it would be easy

In [158]:
scaler=StandardScaler()

In [159]:
standardized_data=scaler.fit_transform(X)

In [160]:
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [161]:
X=standardized_data

In [162]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [163]:
print(X_train.shape,X.shape)

(614, 8) (768, 8)


In [164]:
# Training the model

In [165]:
classifier = svm.SVC(kernel="linear")

In [166]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [167]:
X_train_prediction=classifier.predict(X_train)

In [168]:
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [169]:
training_data_accuracy

0.7866449511400652

In [170]:
# making a predictive system  regarding diabetes

In [195]:
input_data=(2,197,70,45,543,30.5,0.158,53)
input_data_as_numpy_array=np.asarray(input_data)

In [196]:
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

In [197]:
input_data_reshaped

array([[2.00e+00, 1.97e+02, 7.00e+01, 4.50e+01, 5.43e+02, 3.05e+01,
        1.58e-01, 5.30e+01]])

In [198]:
std_data=scaler.transform(input_data_reshaped)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [199]:
std_data

array([[-0.54791859,  2.38188392,  0.04624525,  1.53455054,  4.02192191,
        -0.18943689, -0.94794368,  1.68125866]])

In [200]:
prediction=classifier.predict(std_data)

In [201]:
prediction

array([1])

In [202]:
if prediction[0]==0:
  print('person is not diabetic');
else:
  print('person is  diabetic')

person is  diabetic
